services:
  konvertHR-saas-frontend:
    image: oddo-konverthr-frontend
    container_name: oddoo-konverthr-frontend-container
    # env_file:
    #   - .env.development
    build: .
    ports:
      - "3002:3002"
    restart: always
    # scale: 3
