import { Navigate, Route } from "react-router";
import { all_routes } from "./all_routes";
import TestTheme from "../test-theme";

// Import all lazy-loaded components
import {
  SecurityKeyLogin,
  JobPositionKHR,
  BuisnessLocationKHR,
  BuisnessTypeKHR,
  WorkLocationKHR,
  WorkingSchedulesKHR,
  WorkEntryTypeKHR,
  Login,
  Login2,
  Login3,
  Register,
  Register2,
  Register3,
  TwoStepVerification,
  TwoStepVerification2,
  TwoStepVerification3,
  EmailVerification,
  EmailVerification2,
  EmailVerification3,
  ResetPassword,
  ResetPassword2,
  ResetPassword3,
  ForgotPassword,
  ForgotPassword2,
  ForgotPassword3,
  ResetPasswordSuccess,
  ResetPasswordSuccess2,
  ResetPasswordSuccess3,
  LockScreen,
  Error404,
  Error500,
  UnderMaintenance,
  UnderConstruction,
  AdminDashboard,
  EmployeeDashboard,
  LeadsDasboard,
  DealsDashboard,
  Estimates,
  Chat,
  VoiceCall,
  Videocallss,
  OutgoingCall,
  IncomingCall,
  CallHistory,
  Calendars,
  Email,
  EmailReply,
  Todo,
  TodoList,
  Notes,
  SocialFeed,
  FileManager,
  KanbanView,
  Invoices,
  SuperAdminDashboard,
  Companies,
  Subscription,
  Packages,
  PackagesGrid,
  Domain,
  PurchaseTransaction,
  LayoutDemo,
  ClienttGrid,
  ClientList,
  ClientDetails,
  Project,
  ProjectDetails,
  ProjectList,
  Task,
  TaskDetails,
  TaskBoard,
  ContactList,
  ContactGrid,
  ContactDetails,
  CompaniesGrid,
  CompaniesList,
  CompaniesDetails,
  LeadsGrid,
  LeadsList,
  LeadsDetails,
  DealsGrid,
  DealsDetails,
  DealsList,
  Pipeline,
  Analytics,
  Activity,
  EmployeeList,
  EmployeesGrid,
  Department,
  Designations,
  Policy,
  LeaveAdmin,
  LeaveEmployee,
  LeaveSettings,
  AttendanceAdmin,
  AttendanceEmployee,
  TimeSheet,
  ScheduleTiming,
  OverTime,
  EmployeeDetails,
  Tickets,
  TicketGrid,
  TicketDetails,
  Holidays,
  PerformanceIndicator,
  PerformanceReview,
  PerformanceAppraisal,
  GoalTracking,
  GoalType,
  TrainingList,
  Trainers,
  TrainingType,
  Profilesettings,
  Securitysettings,
  Notificationssettings,
  ConnectedApps,
  Bussinesssettings,
  Seosettings,
  CompanySettings,
  Localizationsettings,
  Prefixes,
  Preference,
  Authenticationsettings,
  Aisettings,
  Salarysettings,
  Approvalsettings,
  Appearance,
  Languageweb,
  Addlanguage,
  InvoiceSettings,
  CustomFields,
  LeaveType,
  EmailSettings,
  Emailtemplates,
  SmsSettings,
  SmsTemplate,
  OtpSettings,
  GdprCookies,
  Maintenancemode,
  PaymentGateways,
  TaxRates,
  Currencies,
  Backup,
  Clearcache,
  Customcss,
  Customjs,
  Cronjob,
  Cronjobschedule,
  Storage,
  RolesPermissions,
  PermissionPage,
  ExpensesReport,
  InvoiceReport,
  PaymentReport,
  ProjectReport,
  Manageusers,
  Blogs,
  BlogCategories,
  BlogComments,
  BlogTags,
  Profile,
  Gallery,
  SearchResult,
  TimeLines,
  Pricing,
  ApiKeys,
  PrivacyPolicy,
  TermsCondition,
  Assets,
  AssetsCategory,
  Knowledgebase,
  Users,
  RolesPermission,
  Permission,
  InvoiceDetails,
  TaskReport,
  UserReports,
  EmployeeReports,
  PayslipReport,
  AttendanceReport,
  LeaveReport,
  DailyReport,
  JobGrid,
  JobList,
  CandidateGrid,
  CandidatesList,
  CandidateKanban,
  RefferalList,
  AddInvoice,
  Payments,
  Expenses,
  ProvidentFund,
  Taxes,
  EmployeeSalary,
  PaySlip,
  PayRoll,
  PayRollOvertime,
  PayRollDeduction,
  Termination,
  Resignation,
  Promotion,
  ComingSoon,
  // Additional lazy-loaded components
  Countries,
  StarterPage,
  Membershipplan,
  MembershipAddon,
  MembershipTransaction,
  DataTable,
  BasicTable,
  DeleteRequest,
  Cities,
  Accordion,
  Avatar,
  Badges,
  Borders,
  Breadcrumb,
  Buttons,
  ButtonsGroup,
  Cards,
  Carousel,
  Colors,
  Dropdowns,
  Grid,
  Images,
  Lightboxes,
  BanIpAddress,
  RangeSlides,
  Media,
  Modals,
  NavTabs,
  Popovers,
  Swiperjs,
  Toasts,
  Sortable,
  BootstrapIcons,
  FlagIcons,
  RemixIcons,
  Leaflet,
  Page,
  Faq,
  States,
  Testimonials,
  ClipBoard,
  Counter,
  DragAndDrop,
  Rating,
  TextEditor,
  Timeline,
  Scrollbar,
  Apexchart,
  PrimeReactChart,
  ChartJSExample,
  FontawesomeIcons,
  MaterialIcons,
  PE7Icons,
  ThemifyIcons,
  TypiconIcons,
  BasicInputs,
  WeatherIcons,
  CheckboxRadios,
  InputGroup,
  GridGutters,
  FormSelect,
  FormMask,
  FileUpload,
  FormHorizontal,
  FormVertical,
  FloatingLabel,
  FormValidation,
  FormSelect2,
  FormWizard,
  FormPikers,
  DataTables,
  TablesBasic,
  IonicIcons,
  Placeholder,
  AlertUi,
  Tooltips,
  Ribbon,
  Categories,
  Budgets,
  BudgetExpenses,
  BudgetRevenues,
  DepartmentKHR,
  RegCategoryKHR,
  AttendancePolicyKHR,
  SkillsKHR,
  IndustriesKHR,
  HrContractTypeKHR,
  EmployeeKHR,
  AdminAttandanceKHR,
  EmployeeAttandanceKHR,
  ShiftModulesKHR,
  LeaveSettingsKHR,
  LeaveAdminKHR,
  LeaveTypesKHR,
  LeaveAllocationKHR,
  LeaveRequestKHR,
  PublicHolidayKHR,
  MendetoryDaysKHR,
  BanksKHR,
  GeoKHR,
  LeaveEmployeeKHR,
  BanksAccountKHR,
  ExpenseCategoryKHR,
  ExpenseKHR,
  EmployeeCalendarsKHR,
  AllApprovalKHR,
  AccruralPlanKHR,
  SalaryRuleCategoryKHR,
  SalaryStructureType,
  SalaryStructureKHR,
  PayslipOtherInputTypes,
  BranchKHR,
  PayslipKHR,

  // BanksAccountKHR,
} from "./lazyRoutes";

// Import third-party components
import { Pagination, Progress, Typography } from "antd";
import { Offcanvas, Spinner } from "react-bootstrap";
import { Video } from "react-feather";
import EmployeeContractKHR from "@/KHRModules/EmployeeContract/EmployeeContractKHR";
import SalaryRuleKHR from "@/KHRModules/payRollModules/SalaryRule/SalaryRule";

const routes = all_routes;

export const publicRoutes = [
  {
    path: "/test-theme",
    name: "Test Theme",
    element: <TestTheme />,
    route: Route,
  },
  {
    path: "/",
    name: "Root",
    element: <Navigate to="/index" />,
    route: Route,
  },
  {
    path: routes.adminDashboard,
    element: <AdminDashboard />,
    route: Route,
  },
  {
    path: routes.employeeDashboard,
    element: <EmployeeDashboard />,
    route: Route,
  },
  {
    path: routes.leadsDashboard,
    element: <LeadsDasboard />,
    route: Route,
  },
  {
    path: routes.dealsDashboard,
    element: <DealsDashboard />,
    route: Route,
  },
  {
    path: routes.estimate,
    element: <Estimates />,
    route: Route,
  },

  {
    path: routes.termination,
    element: <Termination />,
    route: Route,
  },
  {
    path: routes.geoConfigKHR,
    element: <GeoKHR />,
    route: Route,
  },
  {
    path: routes.resignation,
    element: <Resignation />,
    route: Route,
  },
  {
    path: routes.promotion,
    element: <Promotion />,
    route: Route,
  },
  {
    path: routes.trainingType,
    element: <TrainingType />,
    route: Route,
  },

  {
    path: routes.employeeContractKHR,
    element: <EmployeeContractKHR />,
    route: Route,
  },
  {
    path: routes.trainers,
    element: <Trainers />,
    route: Route,
  },
  {
    path: routes.trainingList,
    element: <TrainingList />,
    route: Route,
  },

  // //Application
  {
    path: routes.chat,
    element: <Chat />,
    route: Route,
  },
  {
    path: routes.voiceCall,
    element: <VoiceCall />,
    route: Route,
  },

  {
    path: routes.videoCall,
    element: <Videocallss />,
    route: Route,
  },
  {
    path: routes.outgoingCall,
    element: <OutgoingCall />,
    route: Route,
  },
  {
    path: routes.incomingCall,
    element: <IncomingCall />,
    route: Route,
  },
  {
    path: routes.callHistory,
    element: <CallHistory />,
    route: Route,
  },
  {
    path: routes.socialFeed,
    element: <SocialFeed />,
    route: Route,
  },
  {
    path: routes.kanbanView,
    element: <KanbanView />,
    route: Route,
  },
  {
    path: routes.countries,
    element: <Countries />,
    route: Route,
  },
  {
    path: routes.starter,
    element: <StarterPage />,
    route: Route,
  },
  {
    path: routes.calendar,
    element: <Calendars />,
    route: Route,
  },
  {
    path: routes.superAdminDashboard,
    element: <SuperAdminDashboard />,
    route: Route,
  },

  {
    path: routes.membershipplan,
    element: <Membershipplan />,
    route: Route,
  },
  {
    path: routes.membershipAddon,
    element: <MembershipAddon />,
    route: Route,
  },
  {
    path: routes.membershipTransaction,
    element: <MembershipTransaction />,
    route: Route,
  },
  {
    path: routes.notes,
    element: <Notes />,
    route: Route,
  },
  {
    path: routes.countries,
    element: <Countries />,
    route: Route,
  },
  {
    path: routes.customFields,
    element: <CustomFields />,
    route: Route,
  },
  {
    path: routes.dataTables,
    element: <DataTable />,
    route: Route,
  },
  {
    path: routes.tablesBasic,
    element: <BasicTable />,
    route: Route,
  },

  {
    path: routes.deleteRequest,
    element: <DeleteRequest />,
    route: Route,
  },
  {
    path: routes.cities,
    element: <Cities />,
    route: Route,
  },

  {
    path: routes.accordion,
    element: <Accordion />,
    route: Route,
  },
  {
    path: routes.avatar,
    element: <Avatar />,
    route: Route,
  },
  {
    path: routes.badges,
    element: <Badges />,
    route: Route,
  },
  {
    path: routes.border,
    element: <Borders />,
    route: Route,
  },
  {
    path: routes.breadcrums,
    element: <Breadcrumb />,
    route: Route,
  },
  {
    path: routes.button,
    element: <Buttons />,
    route: Route,
  },
  {
    path: routes.buttonGroup,
    element: <ButtonsGroup />,
    route: Route,
  },
  {
    path: routes.cards,
    element: <Cards />,
    route: Route,
  },
  {
    path: routes.carousel,
    element: <Carousel />,
    route: Route,
  },
  {
    path: routes.colors,
    element: <Colors />,
    route: Route,
  },
  {
    path: routes.dropdowns,
    element: <Dropdowns />,
    route: Route,
  },
  {
    path: routes.grid,
    element: <Grid />,
    route: Route,
  },
  {
    path: routes.images,
    element: <Images />,
    route: Route,
  },
  {
    path: routes.lightbox,
    element: <Lightboxes />,
    route: Route,
  },
  {
    path: routes.media,
    element: <Media />,
    route: Route,
  },
  {
    path: routes.modals,
    element: <Modals />,
    route: Route,
  },
  {
    path: routes.navTabs,
    element: <NavTabs />,
    route: Route,
  },
  {
    path: routes.offcanvas,
    element: <Offcanvas />,
    route: Route,
  },
  {
    path: routes.pagination,
    element: <Pagination />,
    route: Route,
  },
  {
    path: routes.popover,
    element: <Popovers />,
    route: Route,
  },
  {
    path: routes.rangeSlider,
    element: <RangeSlides />,
    route: Route,
  },
  {
    path: routes.progress,
    element: <Progress />,
    route: Route,
  },
  {
    path: routes.spinner,
    element: <Spinner />,
    route: Route,
  },

  {
    path: routes.typography,
    element: <Typography />,
    route: Route,
  },
  {
    path: routes.video,
    element: <Video />,
    route: Route,
  },
  {
    path: routes.sortable,
    element: <Sortable />,
    route: Route,
  },
  {
    path: routes.swiperjs,
    element: <Swiperjs />,
    route: Route,
  },
  {
    path: routes.bootstrapIcons,
    element: <BootstrapIcons />,
    route: Route,
  },
  {
    path: routes.toasts,
    element: <Toasts />,
    route: Route,
  },
  {
    path: routes.mapLeaflet,
    element: <Leaflet />,
    route: Route,
  },
  {
    path: routes.RemixIcons,
    element: <RemixIcons />,
    route: Route,
  },
  {
    path: routes.FlagIcons,
    element: <FlagIcons />,
    route: Route,
  },
  {
    path: routes.banIpAddress,
    element: <BanIpAddress />,
    route: Route,
  },
  {
    path: routes.todo,
    element: <Todo />,
    route: Route,
  },
  {
    path: routes.TodoList,
    element: <TodoList />,
    route: Route,
  },
  {
    path: routes.email,
    element: <Email />,
    route: Route,
  },
  {
    path: routes.EmailReply,
    element: <EmailReply />,
    route: Route,
  },
  {
    path: routes.chat,
    element: <Chat />,
    route: Route,
  },
  {
    path: routes.pages,
    element: <Page />,
    route: Route,
  },

  {
    path: routes.fileManager,
    element: <FileManager />,
    route: Route,
  },
  {
    path: routes.faq,
    element: <Faq />,
    route: Route,
  },

  {
    path: routes.states,
    element: <States />,
    route: Route,
  },
  {
    path: routes.testimonials,
    element: <Testimonials />,
    route: Route,
  },
  {
    path: routes.clipboard,
    element: <ClipBoard />,
    route: Route,
  },
  {
    path: routes.counter,
    element: <Counter />,
    route: Route,
  },
  {
    path: routes.dragandDrop,
    element: <DragAndDrop />,
    route: Route,
  },
  {
    path: routes.rating,
    element: <Rating />,
    route: Route,
  },

  {
    path: routes.textEditor,
    element: <TextEditor />,
    route: Route,
  },
  {
    path: routes.timeLine,
    element: <Timeline />,
    route: Route,
  },
  {
    path: routes.scrollBar,
    element: <Scrollbar />,
    route: Route,
  },
  {
    path: routes.apexChart,
    element: <Apexchart />,
    route: Route,
  },
  {
    path: routes.primeChart,
    element: <PrimeReactChart />,
    route: Route,
  },
  {
    path: routes.chartJs,
    element: <ChartJSExample />,
    route: Route,
  },

  {
    path: routes.fontawesome,
    element: <FontawesomeIcons />,
    route: Route,
  },
  {
    path: routes.materialIcon,
    element: <MaterialIcons />,
    route: Route,
  },
  {
    path: routes.pe7icon,
    element: <PE7Icons />,
    route: Route,
  },

  {
    path: routes.themifyIcon,
    element: <ThemifyIcons />,
    route: Route,
  },
  {
    path: routes.typicon,
    element: <TypiconIcons />,
    route: Route,
  },
  {
    path: routes.basicInput,
    element: <BasicInputs />,
    route: Route,
  },
  {
    path: routes.weatherIcon,
    element: <WeatherIcons />,
    route: Route,
  },
  {
    path: routes.checkboxandRadion,
    element: <CheckboxRadios />,
    route: Route,
  },
  {
    path: routes.inputGroup,
    element: <InputGroup />,
    route: Route,
  },
  {
    path: routes.gridandGutters,
    element: <GridGutters />,
    route: Route,
  },
  {
    path: routes.formSelect,
    element: <FormSelect />,
    route: Route,
  },
  {
    path: routes.formMask,
    element: <FormMask />,
    route: Route,
  },
  {
    path: routes.fileUpload,
    element: <FileUpload />,
    route: Route,
  },
  {
    path: routes.horizontalForm,
    element: <FormHorizontal />,
    route: Route,
  },
  {
    path: routes.verticalForm,
    element: <FormVertical />,
    route: Route,
  },
  {
    path: routes.floatingLable,
    element: <FloatingLabel />,
    route: Route,
  },
  {
    path: routes.formValidation,
    element: <FormValidation />,
    route: Route,
  },
  {
    path: routes.reactSelect,
    element: <FormSelect2 />,
    route: Route,
  },
  {
    path: routes.formWizard,
    element: <FormWizard />,
    route: Route,
  },
  {
    path: routes.formPicker,
    element: <FormPikers />,
    route: Route,
  },
  {
    path: routes.dataTables,
    element: <DataTables />,
    route: Route,
  },
  {
    path: routes.tablesBasic,
    element: <TablesBasic />,
    route: Route,
  },
  {
    path: routes.iconicIcon,
    element: <IonicIcons />,
    route: Route,
  },
  // // {
  // //   path: routes.chart,
  // //   element: <ChartJs />,
  // //   route: Route,
  // // },

  {
    path: routes.placeholder,
    element: <Placeholder />,
    route: Route,
  },

  {
    path: routes.alert,
    element: <AlertUi />,
    route: Route,
  },
  {
    path: routes.tooltip,
    element: <Tooltips />,
    route: Route,
  },
  {
    path: routes.ribbon,
    element: <Ribbon />,
    route: Route,
  },
  {
    path: routes.categories,
    element: <Categories />,
    route: Route,
  },
  {
    path: routes.budgets,
    element: <Budgets />,
    route: Route,
  },
  {
    path: routes.budgetexpenses,
    element: <BudgetExpenses />,
    route: Route,
  },
  {
    path: routes.budgetrevenues,
    element: <BudgetRevenues />,
    route: Route,
  },
  {
    path: routes.tickets,
    element: <Tickets />,
    route: Route,
  },
  {
    path: routes.ticketGrid,
    element: <TicketGrid />,
    route: Route,
  },
  {
    path: routes.ticketDetails,
    element: <TicketDetails />,
    route: Route,
  },
  {
    path: routes.performanceIndicator,
    element: <PerformanceIndicator />,
    route: Route,
  },
  {
    path: routes.holidays,
    element: <Holidays />,
    route: Route,
  },
  {
    path: routes.performanceReview,
    element: <PerformanceReview />,
    route: Route,
  },
  {
    path: routes.performanceAppraisal,
    element: <PerformanceAppraisal />,
    route: Route,
  },
  {
    path: routes.goalTracking,
    element: <GoalTracking />,
    route: Route,
  },
  {
    path: routes.goalType,
    element: <GoalType />,
    route: Route,
  },
  {
    path: routes.trainingList,
    element: <TrainingList />,
    route: Route,
  },
  {
    path: routes.trainers,
    element: <Trainers />,
    route: Route,
  },
  {
    path: routes.trainingType,
    element: <TrainingType />,
    route: Route,
  },

  {
    path: routes.Horizontal,
    element: <LayoutDemo />,
    route: Route,
  },
  {
    path: routes.Detached,
    element: <LayoutDemo />,
    route: Route,
  },
  {
    path: routes.Modern,
    element: <LayoutDemo />,
    route: Route,
  },
  {
    path: routes.TwoColumn,
    element: <LayoutDemo />,
    route: Route,
  },
  {
    path: routes.Hovered,
    element: <LayoutDemo />,
    route: Route,
  },
  {
    path: routes.layoutBox,
    element: <LayoutDemo />,
    route: Route,
  },
  {
    path: routes.HorizontalSingle,
    element: <LayoutDemo />,
    route: Route,
  },
  {
    path: routes.HorizontalOverlay,
    element: <LayoutDemo />,
    route: Route,
  },
  {
    path: routes.HorizontalBox,
    element: <LayoutDemo />,
    route: Route,
  },
  {
    path: routes.MenuAside,
    element: <LayoutDemo />,
    route: Route,
  },
  {
    path: routes.Transparent,
    element: <LayoutDemo />,
    route: Route,
  },
  {
    path: routes.WithoutHeader,
    element: <LayoutDemo />,
    route: Route,
  },
  {
    path: routes.layoutRtl,
    element: <LayoutDemo />,
    route: Route,
  },
  {
    path: routes.layoutDark,
    element: <LayoutDemo />,
    route: Route,
  },

  // //Settings

  {
    path: routes.profilesettings,
    element: <Profilesettings />,
    route: Route,
  },
  {
    path: routes.securitysettings,
    element: <Securitysettings />,
    route: Route,
  },
  {
    path: routes.notificationssettings,
    element: <Notificationssettings />,
    route: Route,
  },
  {
    path: routes.connectedApps,
    element: <ConnectedApps />,
    route: Route,
  },
  {
    path: routes.bussinessSettings,
    element: <Bussinesssettings />,
    route: Route,
  },
  {
    path: routes.seoSettings,
    element: <Seosettings />,
    route: Route,
  },
  {
    path: routes.companySettings,
    element: <CompanySettings />,
    route: Route,
  },
  {
    path: routes.localizationSettings,
    element: <Localizationsettings />,
    route: Route,
  },
  {
    path: routes.prefixes,
    element: <Prefixes />,
    route: Route,
  },
  {
    path: routes.preference,
    element: <Preference />,
    route: Route,
  },
  {
    path: routes.authenticationSettings,
    element: <Authenticationsettings />,
    route: Route,
  },
  {
    path: routes.aiSettings,
    element: <Aisettings />,
    route: Route,
  },
  {
    path: routes.salarySettings,
    element: <Salarysettings />,
    route: Route,
  },
  {
    path: routes.approvalSettings,
    element: <Approvalsettings />,
    route: Route,
  },
  {
    path: routes.appearance,
    element: <Appearance />,
    route: Route,
  },
  {
    path: routes.languageWeb,
    element: <Languageweb />,
    route: Route,
  },
  {
    path: routes.addLanguage,
    element: <Addlanguage />,
    route: Route,
  },
  {
    path: routes.invoiceSettings,
    element: <InvoiceSettings />,
    route: Route,
  },
  {
    path: routes.customFields,
    element: <CustomFields />,
    route: Route,
  },
  {
    path: routes.leaveType,
    element: <LeaveType />,
    route: Route,
  },
  {
    path: routes.emailSettings,
    element: <EmailSettings />,
    route: Route,
  },
  {
    path: routes.emailTemplates,
    element: <Emailtemplates />,
    route: Route,
  },
  {
    path: routes.smsSettings,
    element: <SmsSettings />,
    route: Route,
  },
  {
    path: routes.smsTemplate,
    element: <SmsTemplate />,
    route: Route,
  },
  {
    path: routes.otpSettings,
    element: <OtpSettings />,
    route: Route,
  },
  {
    path: routes.gdprCookies,
    element: <GdprCookies />,
    route: Route,
  },
  {
    path: routes.maintenanceMode,
    element: <Maintenancemode />,
    route: Route,
  },

  {
    path: routes.paymentGateways,
    element: <PaymentGateways />,
    route: Route,
  },
  {
    path: routes.taxRates,
    element: <TaxRates />,
    route: Route,
  },
  {
    path: routes.currencies,
    element: <Currencies />,
    route: Route,
  },
  {
    path: routes.backup,
    element: <Backup />,
    route: Route,
  },
  {
    path: routes.clearcache,
    element: <Clearcache />,
    route: Route,
  },
  {
    path: routes.customCss,
    element: <Customcss />,
    route: Route,
  },
  {
    path: routes.customJs,
    element: <Customjs />,
    route: Route,
  },
  {
    path: routes.cronjob,
    element: <Cronjob />,
    route: Route,
  },
  {
    path: routes.Cronjobschedule,
    element: <Cronjobschedule />,
    route: Route,
  },
  {
    path: routes.storage,
    element: <Storage />,
    route: Route,
  },

  {
    path: routes.rolesPermissions,
    element: <RolesPermissions />,
    route: Route,
  },
  {
    path: routes.permissionpage,
    element: <PermissionPage />,
    route: Route,
  },
  {
    path: routes.expensesreport,
    element: <ExpensesReport />,
    route: Route,
  },
  {
    path: routes.invoicereport,
    element: <InvoiceReport />,
    route: Route,
  },
  {
    path: routes.paymentreport,
    element: <PaymentReport />,
    route: Route,
  },
  {
    path: routes.projectreport,
    element: <ProjectReport />,
    route: Route,
  },
  {
    path: routes.manageusers,
    element: <Manageusers />,
    route: Route,
  },
  {
    path: routes.blogs,
    element: <Blogs />,
    route: Route,
  },
  {
    path: routes.blogCategories,
    element: <BlogCategories />,
    route: Route,
  },
  {
    path: routes.blogComments,
    element: <BlogComments />,
    route: Route,
  },
  {
    path: routes.blogTags,
    element: <BlogTags />,
    route: Route,
  },

  {
    path: routes.profile,
    element: <Profile />,
    route: Route,
  },
  {
    path: routes.gallery,
    element: <Gallery />,
    route: Route,
  },
  {
    path: routes.searchresult,
    element: <SearchResult />,
    route: Route,
  },
  {
    path: routes.timeline,
    element: <TimeLines />,
    route: Route,
  },
  {
    path: routes.pricing,
    element: <Pricing />,
    route: Route,
  },
  {
    path: routes.apikey,
    element: <ApiKeys />,
    route: Route,
  },

  {
    path: routes.privacyPolicy,
    element: <PrivacyPolicy />,
    route: Route,
  },
  {
    path: routes.termscondition,
    element: <TermsCondition />,
    route: Route,
  },
  {
    path: routes.assetList,
    element: <Assets />,
    route: Route,
  },
  {
    path: routes.assetCategories,
    element: <AssetsCategory />,
    route: Route,
  },
  {
    path: routes.knowledgebase,
    element: <Knowledgebase />,
    route: Route,
  },
  {
    path: routes.activity,
    element: <Activity />,
    route: Route,
  },
  {
    path: routes.users,
    element: <Users />,
    route: Route,
  },
  {
    path: routes.rolePermission,
    element: <RolesPermission />,
    route: Route,
  },
  {
    path: routes.permissionpage,
    element: <Permission />,
    route: Route,
  },
  {
    path: routes.invoiceDetails,
    element: <InvoiceDetails />,
    route: Route,
  },
  {
    path: routes.taskreport,
    element: <TaskReport />,
    route: Route,
  },
  {
    path: routes.userreport,
    element: <UserReports />,
    route: Route,
  },
  {
    path: routes.employeereport,
    element: <EmployeeReports />,
    route: Route,
  },
  {
    path: routes.employeedetails,
    element: <EmployeeDetails />,
    route: Route,
  },
  {
    path: routes.payslipreport,
    element: <PayslipReport />,
    route: Route,
  },
  {
    path: routes.attendancereport,
    element: <AttendanceReport />,
    route: Route,
  },
  {
    path: routes.leavereport,
    element: <LeaveReport />,
    route: Route,
  },
  {
    path: routes.dailyreport,
    element: <DailyReport />,
    route: Route,
  },
  {
    path: routes.jobgrid,
    element: <JobGrid />,
    route: Route,
  },
  {
    path: routes.joblist,
    element: <JobList />,
    route: Route,
  },
  {
    path: routes.candidatesGrid,
    element: <CandidateGrid />,
    route: Route,
  },
  {
    path: routes.candidateslist,
    element: <CandidatesList />,
    route: Route,
  },
  {
    path: routes.candidateskanban,
    element: <CandidateKanban />,
    route: Route,
  },
  {
    path: routes.refferal,
    element: <RefferalList />,
    route: Route,
  },
  {
    path: routes.clientgrid,
    element: <ClienttGrid />,
    route: Route,
  },
  {
    path: routes.clientlist,
    element: <ClientList />,
    route: Route,
  },
  {
    path: routes.clientdetils,
    element: <ClientDetails />,
    route: Route,
  },
  {
    path: routes.project,
    element: <Project />,
    route: Route,
  },
  {
    path: routes.projectdetails,
    element: <ProjectDetails />,
    route: Route,
  },
  {
    path: routes.projectlist,
    element: <ProjectList />,
    route: Route,
  },
  {
    path: routes.tasks,
    element: <Task />,
    route: Route,
  },
  {
    path: routes.tasksdetails,
    element: <TaskDetails />,
    route: Route,
  },
  {
    path: routes.taskboard,
    element: <TaskBoard />,
    route: Route,
  },
  // {
  //   path: routes.invoices,
  //   element: <Invoices />,
  //   route: Route,
  // },
  {
    path: routes.invoice,
    element: <Invoices />,
    route: Route,
  },
  {
    path: routes.addinvoice,
    element: <AddInvoice />,
    route: Route,
  },

  {
    path: routes.invoicesdetails,
    element: <InvoiceDetails />,
    route: Route,
  },
  {
    path: routes.payments,
    element: <Payments />,
    route: Route,
  },
  {
    path: routes.expenses,
    element: <Expenses />,
    route: Route,
  },
  {
    path: routes.providentfund,
    element: <ProvidentFund />,
    route: Route,
  },
  {
    path: routes.taxes,
    element: <Taxes />,
    route: Route,
  },
  {
    path: routes.employeesalary,
    element: <EmployeeSalary />,
    route: Route,
  },
  {
    path: routes.payslip,
    element: <PaySlip />,
    route: Route,
  },
  {
    path: routes.payrollAddition,
    element: <PayRoll />,
    route: Route,
  },
  {
    path: routes.payrollOvertime,
    element: <PayRollOvertime />,
    route: Route,
  },
  {
    path: routes.payrollDeduction,
    element: <PayRollDeduction />,
    route: Route,
  },
  {
    path: routes.employeeList,
    element: <EmployeeList />,
    route: Route,
  },
  {
    path: routes.employeeGrid,
    element: <EmployeesGrid />,
    route: Route,
  },
  {
    path: routes.departments,
    element: <Department />,
    route: Route,
  },
  {
    path: routes.branchKHR,
    element: <BranchKHR />,
    route: Route,
  },
  {
    path: routes.workLocationKHR,
    element: <WorkLocationKHR />,
    route: Route,
  },
  {
    path: routes.workingScheduleKHR,
    element: <WorkingSchedulesKHR />,
    route: Route,
  },
  {
    path: routes.workEntryTypeKHR,
    element: <WorkEntryTypeKHR />,
    route: Route,
  },
  {
    path: routes.skillsKHR,
    element: <SkillsKHR />,
    route: Route,
  },
  {
    path: routes.industriesKHR,
    element: <IndustriesKHR />,
    route: Route,
  },
  {
    path: routes.banksKHR,
    element: <BanksKHR />,
    route: Route,
  },
  {
    path: routes.banksAccountKHR,
    element: <BanksAccountKHR />,
    route: Route,
  },
  {
    path: routes.expenseCategoryKHR,
    element: <ExpenseCategoryKHR />,
    route: Route,
  },
  {
    path: routes.accruralPlanKHR,
    element: <AccruralPlanKHR />,
    route: Route,
  },
  {
    path: routes.hrContractTypeKHR,
    element: <HrContractTypeKHR />,
    route: Route,
  },
  {
    path: routes.employeeKHR,
    element: <EmployeeKHR />,
    route: Route,
  },
  {
    path: routes.expenseKHR,
    element: <ExpenseKHR />,
    route: Route,
  },
  {
    path: routes.approvalKHR,
    element: <AllApprovalKHR />,
    route: Route,
  },
  {
    path: routes.employeeCalenderKHR,
    element: <EmployeeCalendarsKHR />,
    route: Route,
  },
  {
    path: routes.attendanceAdminKHR,
    element: <AdminAttandanceKHR />,
    route: Route,
  },
  {
    path: routes.attendaceEmployeeKHR,
    element: <EmployeeAttandanceKHR />,
    route: Route,
  },
  {
    path: routes.shiftModulesKHR,
    element: <ShiftModulesKHR />,
    route: Route,
  },
  {
    path: routes.leaveSettingsKHR,
    element: <LeaveSettingsKHR />,
    route: Route,
  },
  {
    path: routes.salaryStructureTypeKHR,
    element: <SalaryStructureType />,
    route: Route,
  },
  {
    path: routes.salaryStructureKHR,
    element: <SalaryStructureKHR />,
    route: Route,
  },
  {
    path: routes.SalaryRuleKHR,
    element: <SalaryRuleKHR />,
    route: Route,
  },
  {
    path: routes.payslipOtherInputTypeKHR,
    element: <PayslipOtherInputTypes />,
    route: Route,
  },
  {
    path: routes.payslipKHR,
    element: <PayslipKHR />,
    route: Route,
  },
  // {
  //   path: routes.SalaryStructure,
  //   element: <SalaryStructureType />,
  //   route: Route,
  // },
  {
    path: routes.leaveEmployeeKHR,
    element: <LeaveEmployeeKHR />,
    route: Route,
  },
  {
    path: routes.leaveAdminKHR,
    element: <LeaveAdminKHR />,
    route: Route,
  },
  {
    path: routes.leaveTypesKHR,
    element: <LeaveTypesKHR />,
    route: Route,
  },
  {
    path: routes.leaveAllocationKHR,
    element: <LeaveAllocationKHR />,
    route: Route,
  },
  {
    path: routes.leaveRequestKHR,
    element: <LeaveRequestKHR />,
    route: Route,
  },
  {
    path: routes.publicHolidayKHR,
    element: <PublicHolidayKHR />,
    route: Route,
  },
  {
    path: routes.mendetoryDaysKHR,
    element: <MendetoryDaysKHR />,
    route: Route,
  },
  {
    path: routes.SalaryRuleCategoryKHR,
    element: <SalaryRuleCategoryKHR />,
    route: Route,
  },
  {
    path: routes.buisnessTypeKHR,
    element: <BuisnessTypeKHR />,
    route: Route,
  },
  {
    path: routes.designations,
    element: <Designations />,
    route: Route,
  },
  {
    path: routes.policy,
    element: <Policy />,
    route: Route,
  },
  {
    path: routes.leaveadmin,
    element: <LeaveAdmin />,
    route: Route,
  },
  {
    path: routes.leaveemployee,
    element: <LeaveEmployee />,
    route: Route,
  },
  {
    path: routes.leavesettings,
    element: <LeaveSettings />,
    route: Route,
  },
  {
    path: routes.attendanceadmin,
    element: <AttendanceAdmin />,
    route: Route,
  },
  {
    path: routes.attendanceemployee,
    element: <AttendanceEmployee />,
    route: Route,
  },
  {
    path: routes.departmentsKHR,
    element: <DepartmentKHR />,
    route: Route,
  },
  {
    path: routes.regCategoryKHR,
    element: <RegCategoryKHR />,
    route: Route,
  },
  {
    path: routes.jobPositionsKHR,
    element: <JobPositionKHR />,
    route: Route,
  },
  {
    path: routes.buisnessLocationKHR,
    element: <BuisnessLocationKHR />,
    route: Route,
  },
  {
    path: routes.AttendancePolicyKHR,
    element: <AttendancePolicyKHR />,
    route: Route,
  },
  {
    path: routes.buisnessTypeKHR,
    element: <BuisnessTypeKHR />,
    route: Route,
  },
  {
    path: routes.timesheet,
    element: <TimeSheet />,
    route: Route,
  },
  {
    path: routes.scheduletiming,
    element: <ScheduleTiming />,
    route: Route,
  },
  {
    path: routes.overtime,
    element: <OverTime />,
    route: Route,
  },

  // //crm
  {
    path: routes.contactList,
    element: <ContactList />,
    route: Route,
  },
  {
    path: routes.contactGrid,
    element: <ContactGrid />,
    route: Route,
  },
  {
    path: routes.contactDetails,
    element: <ContactDetails />,
    route: Route,
  },
  {
    path: routes.companiesGrid,
    element: <CompaniesGrid />,
    route: Route,
  },
  {
    path: routes.companiesList,
    element: <CompaniesList />,
    route: Route,
  },
  {
    path: routes.companiesDetails,
    element: <CompaniesDetails />,
    route: Route,
  },
  {
    path: routes.leadsGrid,
    element: <LeadsGrid />,
    route: Route,
  },
  {
    path: routes.leadsList,
    element: <LeadsList />,
    route: Route,
  },
  {
    path: routes.leadsDetails,
    element: <LeadsDetails />,
    route: Route,
  },
  {
    path: routes.dealsGrid,
    element: <DealsGrid />,
    route: Route,
  },
  {
    path: routes.dealsList,
    element: <DealsList />,
    route: Route,
  },
  {
    path: routes.dealsDetails,
    element: <DealsDetails />,
    route: Route,
  },
  {
    path: routes.pipeline,
    element: <Pipeline />,
    route: Route,
  },
  {
    path: routes.analytics,
    element: <Analytics />,
    route: Route,
  },
  {
    path: routes.superAdminCompanies,
    element: <Companies />,
    route: Route,
  },
  {
    path: routes.superAdminSubscriptions,
    element: <Subscription />,
    route: Route,
  },
  {
    path: routes.superAdminPackages,
    element: <Packages />,
    route: Route,
  },
  {
    path: routes.superAdminPackagesGrid,
    element: <PackagesGrid />,
    route: Route,
  },
  {
    path: routes.superAdminDomain,
    element: <Domain />,
    route: Route,
  },
  {
    path: routes.superAdminPurchaseTransaction,
    element: <PurchaseTransaction />,
    route: Route,
  },
];

export const authRoutes = [
  {
    path: routes.comingSoon,
    element: <ComingSoon />,
    route: Route,
  },
  {
    path: routes.login,
    element: <Login />,
    route: Route,
  },
  {
    path: routes.planActivationKHR,
    element: <SecurityKeyLogin />,
    route: Route,
  },

  {
    path: routes.login2,
    element: <Login2 />,
    route: Route,
  },
  {
    path: routes.login3,
    element: <Login3 />,
    route: Route,
  },
  {
    path: routes.register,
    element: <Register />,
    route: Route,
  },
  {
    path: routes.twoStepVerification,
    element: <TwoStepVerification />,
    route: Route,
  },
  {
    path: routes.twoStepVerification2,
    element: <TwoStepVerification2 />,
    route: Route,
  },
  {
    path: routes.twoStepVerification3,
    element: <TwoStepVerification3 />,
    route: Route,
  },
  {
    path: routes.emailVerification,
    element: <EmailVerification />,
    route: Route,
  },
  {
    path: routes.emailVerification2,
    element: <EmailVerification2 />,
    route: Route,
  },
  {
    path: routes.emailVerification3,
    element: <EmailVerification3 />,
    route: Route,
  },
  {
    path: routes.register,
    element: <Register />,
    route: Route,
  },
  {
    path: routes.register2,
    element: <Register2 />,
    route: Route,
  },
  {
    path: routes.register3,
    element: <Register3 />,
    route: Route,
  },
  {
    path: routes.resetPassword,
    element: <ResetPassword />,
    route: Route,
  },
  {
    path: routes.resetPassword2,
    element: <ResetPassword2 />,
    route: Route,
  },
  {
    path: routes.resetPassword3,
    element: <ResetPassword3 />,
    route: Route,
  },
  {
    path: routes.forgotPassword,
    element: <ForgotPassword />,
    route: Route,
  },
  {
    path: routes.forgotPassword2,
    element: <ForgotPassword2 />,
    route: Route,
  },
  {
    path: routes.forgotPassword3,
    element: <ForgotPassword3 />,
    route: Route,
  },
  {
    path: routes.error404,
    element: <Error404 />,
    route: Route,
  },
  {
    path: routes.error500,
    element: <Error500 />,
    route: Route,
  },
  {
    path: routes.underMaintenance,
    element: <UnderMaintenance />,
    route: Route,
  },
  {
    path: routes.underConstruction,
    element: <UnderConstruction />,
  },
  {
    path: routes.lockScreen,
    element: <LockScreen />,
  },
  {
    path: routes.resetPasswordSuccess,
    element: <ResetPasswordSuccess />,
  },
  {
    path: routes.resetPasswordSuccess2,
    element: <ResetPasswordSuccess2 />,
  },
  {
    path: routes.resetPasswordSuccess3,
    element: <ResetPasswordSuccess3 />,
  },
];
