name: Auto Deploy (Production & Staging)

on:
  push:
    branches:
      - main
      - staging

jobs:
  # =========================
  # PRODUCTION DEPLOY
  # =========================
  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Production via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/odooproduction.konverthr.com
            git pull origin main
            docker compose up -d --build odooproduction-konverthr-com

  # =========================
  # STAGING DEPLOY
  # =========================
  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Staging via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/odoosaas.konverthr.com
            git pull origin staging
            docker compose up -d --build konvertHR-saas-frontend
